language: node_js
os:
  - linux
  - osx
  - windows
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  # - "10"
  # - "11"
  - "12"
  # - "13"
  # - "14"
  # - lts/*
  # - node
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm i -g yarn
scripts:
  - set -e
  - yarn install
  - yarn run prettier:write
  - yarn run lint:write
  - yarn run jscpd
  - yarn run test
  - yarn run test:junit
  - yarn run build
# after_script:
  - if [[ $TRAVIS_NODE_VERSION == '12' && $TRAVIS_OS_NAME == 'linux' ]]; then yarn run docs;
    if [[ $LANGUAGE == 'typescript' ]]; then sonar-scanner; fi;
    fi
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "templ-project"
    token:
      secure: tiei3agoKi1TWEWSDcl60lvxDOQMaIjYFW15lJwVVSVD+NMGTQotHkyjsGYJBtAhHVo8VeafrB8VkyRyQ/2n0mOcB5uUMdfHsBHS4AQ1tfOmw2Nnw7CGfd5O6hZmmw1sY7HrcvW+wb0AY7GfC/lNBP5wFIowc2wEvR4xcuYaoIo1kElcP96TkTJbdZnF4TcLWcUH6M63G862ebNGvL4mPHCf7cJVM6Yjt/PMav5FAkuaNGdWaSJYITteRz9NGynKBOJdMAMlUARyRxVYkAw08qPwKV8HpcGbhzlwFRSrw5NJY38cvQgK9QdSzET1RFoXXJ/AAtMVV5yg2+ywVtgjyQ8I2LCZgvC/qgrtU5AHklJUf8u1rdRZDrZ/xCT0kJuLg/EaWKT/f1ZgIF4D9A+fnda41O9l27Kon41lXjhkiAxoYYIhfrKH1/HxmdePSBtEB9g8vpUE2QwzjBhBSAnMlDd+8LigAbZUZoXc+35GLOqy/ePAPEvzZiuIs/ydZ9yDJUCeVGc0seoOQRpaNXy2YaL+Q7X16CcBVtFcV01BxWDeoYfZUj7IguiQt69t56vcg179X40QT9PH/gm7AZfnIhefOypiwIQFdCjQ0CYAp50QDP+fasYxIrui+Oi/3vvBzNOsZ68d6/mvlauUyFM2hmMOZ0LM09ZOqrORIgqBZkY=
